package.json
yarn.lock

https://github.com/rwjblue/release-it-lerna-changelog

chore(dev-deps): add release-it-lerna-changelog

---

RELEASE.md
package.json
yarn.lock

I'd like to switch back to release-it but currently I'm having trouble with it. I'm using the same setup as eslint-plugin-ember for now.

Switch from release-it to lerna-changelog

---

tests/config-setup.js

Very similar to existing rule setup tests.

Add tests to ensure configs are exported and mentioned in README

---

.github/workflows/ci.yml

Node 14 was released this month.

Begin testing under Node 14

---

tests/rule-setup.js

Make it clear which rule is causing a failure and why.

Make failures more clear/actionable in rule setup tests

---

lib/config/typescript.js

Fix incorrect rule severity level in `typescript` config

---

package.json

This will save time by only running linting on changed files.
https://eslint.org/docs/user-guide/command-line-interface#caching

Enable eslint caching internally

---

.eslintrc.js

https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/prefer-object-rule.md

Enable `eslint-plugin/prefer-object-rule` rule internally

---

lib/config/ember.js

https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-get.md

Enable `useOptionalChaining` option on `ember/no-get` rule in `ember` config

---

lib/config/base.js

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-flat-map.md

Stop disabling `unicorn/prefer-flat-map` rule in `base` config

---

lib/config/base.js

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-optional-catch-binding.md

Stop disabling `unicorn/prefer-optional-catch-binding` rule in `base` config

---

lib/config/ember.js

https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/prefer-ember-test-helpers.md

Enable `ember/prefer-ember-test-helpers` rule in `ember` config

---

lib/config/ember.js

https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-test-this-render.md

Enable `ember/no-test-this-render` rule in `ember` config

---

.github/workflows/ci.yml
README.md
package.json

Drop Node 13 support

---

lib/config/ember.js

https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-invalid-test-waiters.md

Enable `ember/no-invalid-test-waiters` rule in `ember` config

---

.eslintrc.js
README.md
docs/rules/no-assert-ok-find.md
docs/rules/no-for-of.md
docs/rules/no-handlebar-interpolation.md
docs/rules/no-lazy-arrow-functions.md
docs/rules/no-missing-tests.md
docs/rules/no-modifying-immutable-properties.md
docs/rules/no-test-expect-assertion-count.md
docs/rules/no-test-return-value.md
docs/rules/require-await-function.md
docs/rules/use-call-count-test-assert.md
package.json
yarn.lock

https://github.com/eslint/eslint-plugin-markdown

Add eslint-plugin-markdown

---

.npmpackagejsonlintrc.json
package.json
yarn.lock

https://www.npmjs.com/package/npm-package-json-lint

Add npm-package-json-lint

---

lib/config/typescript.js

[v3 introduced this simplification](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0)

refactor(ts): simplify config

---

lib/config/ember.js

https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-side-effects.md

Enable `checkPlainGetters` option on `ember/no-side-effects` rule

---

lib/config/ember.js

https://github.com/ember-cli/eslint-plugin-ember/releases/tag/v9.0.0
Follow-up to #200.

Cleanup unnecessary configuration resulting from eslint-plugin-ember v9

---

RELEASE.md
package.json
yarn.lock

https://github.com/rwjblue/release-it-lerna-changelog

Automate release process with release-it-lerna-changelog

---

lib/config/base.js

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-lonely-if.md

Disable `unicorn/no-lonely-if` rule in `base` config

---

lib/config/base.js

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-for-each.md

Disable `unicorn/no-array-for-each` rule in `base` config

---

lib/index.js
package.json

Makes it easier to add or remove rules.
https://www.npmjs.com/package/requireindex

Use `requireindex` to export rules and configs

---

lib/config/base.js
lib/utils/flat.js
package.json
yarn.lock

https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v31.0.0

chore(deps): update to eslint-plugin-unicorn v31

---

lib/config/base.js
lib/utils/flat.js
package.json
yarn.lock

This reverts commit 18ccdfde0e2f47bad4f33c032b9ad772a444a6b7.
Revert #381 to avoid breaking change for now.

Revert "chore(deps): update to eslint-plugin-unicorn v31"

---

.github/workflows/ci.yml
README.md
lib/rules/no-missing-tests.js
lib/utils/flat.js
package.json
tests/lib/rules/use-call-count-test-assert.js
tests/rule-setup.js

* Drop Node 10 support (end-of-life 2021-04) (and use native flat / flatMap functions)
* Drop Node 15 support (end-of-life 2021-06-01)

Drop support for Node 10 and Node 15

---

lib/config/base.js

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-prototype-methods.md

Fix typo when disabling `unicorn/prefer-prototype-methods` rule

---

docs/rules/no-assert-ok-find.md
docs/rules/no-test-return-value.md
tests/rule-setup.js

Mention which rules provide suggestions in individual rule docs

---

README.md
docs/rules/require-await-function.md
docs/rules/use-call-count-test-assert.md
docs/rules/use-ember-find.md
tests/rule-setup.js

Matches the format in:
* https://github.com/ember-cli/eslint-plugin-ember#-rules
* https://github.com/ember-template-lint/ember-template-lint#rules
* https://github.com/platinumazure/eslint-plugin-qunit#rules
* https://github.com/sindresorhus/eslint-plugin-unicorn#rules

Improve rules table header and fixable notices

---

docs/rules/_TEMPLATE_.md

The style of the fixable notice changed so removing the old style here.

Tweak rule template

---

lib/rules/no-assert-ok-find.js
lib/rules/no-handlebar-interpolation.js
lib/rules/no-missing-tests.js
lib/rules/no-restricted-files.js
lib/rules/no-test-return-value.js
lib/rules/no-translation-key-interpolation.js
lib/rules/require-await-function.js
lib/rules/use-call-count-test-assert.js
lib/rules/use-ember-find.js
tests/rule-setup.js

* Use single-line format
* Add test that each rule has this comment

Add test for tweaked rule jsdoc type comment

---

.eslintrc.js

Forgot to include in: https://github.com/square/eslint-plugin-square/pull/691

Remove unnecessary lint rule disable config

---

docs/rules/_TEMPLATE_.md

Update rule doc template based on eslint-doc-generator

---

package.json
yarn.lock

Revert @square/prettier-config to v1 to fix inconsistent Prettier quotes configurations 

---

package.json
yarn.lock

more preparation for v26
- https://github.com/square/eslint-plugin-square/issues/880#issuecomment-1614747317
- https://github.com/square/eslint-plugin-square/pull/886#issuecomment-1614743135

Drop Node v19 Support

---

.github/workflows/ci.yml
README.md
package.json

🚨 BREAKING 🚨 
also, start testing v21

Drop Node v16 support

---

.github/workflows/release.yml

Fix the releaser branch from main to master.

chore: Fix Releaser branch (main->master)

---

RELEASE.md

- bump deps to cut a new release
- add instructions on how to release bump dependencies only!

fix(deps): bump deps to cut a new release
