README.md, lib/config/typescript.js, lib/index.js, package.json, yarn.lock
Our team has a framework-less, browser-based project that uses TypeScript. We'd like to use `eslint-plugin-square` to drive our linting going forward. This PR is most of our current configuration minus overlaps with `base`. (We'll continue to use plugins specific to our test framework and assertion library.)
=> Add `typescript` config

README.md, package.json
Node 11 is end-of-life.
This is technically a breaking change. I originally intended to include this was the v13 release.
=> Drop Node 11 support

README.md, lib/config/react.js, lib/index.js, package.json, yarn.lock
This commit adds a simple ESLint configuration for React that extends the base JavaScript configuration and React-recommended plugin. It also includes a few specific rules that are also enforced in the TypeScript configuration.
=> Add `react` configuration

lib/config/react.js
React component file names are typically defined in PascalCase to match the exported variable names, which are also PascalCase in an effort to avoid potentially ambiguity due to conflicts with HTML element names.
=> Allow PascalCase component filenames in `react` config

package.json, yarn.lock
Dependency ranges should be wide using a caret to give consumers more flexibility. Dev-dependency versions should be fixed.
https://docs.renovatebot.com/dependency-pinning/
=> Widen dependency range for eslint-plugin-prettier

lib/config/typescript.js
tl;dr `eslint/no-useless-constructor` doesn't understand all TypeScript syntax 🤯
as you can see in [this example repo](https://github.com/maxbeatty/example-eslint/commit/65b2499bfadfaf2119fae1e90d0866ce2cb50b35), `declare class Animal` syntax from TypeScript causes a thrown error in `no-useless-constructor` preventing eslint from completing.
```ts
declare class Animal {
constructor(age: number);
makeNoise: () => string;
}
```
[overriding the rule and replacing with @typescript-eslint/no-useless-constructor variant](https://github.com/maxbeatty/example-eslint/commit/dd886d002f44a4ecb93a130ee8b31793a1680641#diff-1dc6ee56b778cd91e0327b52aaeaa1b9R8-R9) (which is more robust for TypeScript) allows eslint to complete and properly report useless constructors.
[using this …
=> Disable `no-useless-constructor` rule in `typescript` config

lib/config/react.js
These changes represent overrides and rules specified in my team ESLint configuration that would probably be of more use on a horizontal scale. No rush on the merge!
-Update kebab-case file name regular expression to accept multiple `.` instances and disallow capitalized first letter
-Alphabetize rule property names
-Allow non-declarative arrow functions
-Allow file extensions for imports due to webpack support/requirement
-Update component file name regular expression to allow multiple `.` instances
-Add file name override for `setupTests` file required by create-react-app API
=> Tweak filename regexes and other rules in `react` config

lib/config/base.js, lib/config/ember.js, lib/config/react.js, lib/config/typescript.js, lib/utils/filenames.js, tests/lib/utils/filenames.js
Currently, the regex used by `ember` and `typescript` only allows filenames like `foo-bar.d.js`. The `react` regex allows for multiple dots and expanded suffixes such as `apple.stories.test.jsx`. This PR abstracts the regex being used by the three configurations making it testable.
As a bonus, I tested the `react` component pascal regex.
=> Standardize filename regexes

README.md, docs/rules/no-assert-ok-find.md, docs/rules/no-focused-tests.md, docs/rules/no-lazy-arrow-functions.md, docs/rules/no-test-expect-assertion-count.md, docs/rules/no-test-return-value.md, docs/rules/no-translation-key-interpolation.md, docs/rules/require-await-function.md, docs/rules/use-call-count-test-assert.md, docs/rules/use-ember-find.md, tests/rule-setup.js
Matches the eslint core plugin rule docs (example: https://eslint.org/docs/rules/no-extra-semi).
This makes it much easier to gain a complete picture of the rule by looking at its rule doc (without depending on the overall README.md).
And adds a test to ensure the docs are correct.
Based on a change I made: https://github.com/ember-cli/eslint-plugin-ember/pull/759
=> Update each rule doc to mention what config enables the rule

lib/utils/filenames.js, tests/lib/utils/filenames.js
=> Kebab-case filename restrictions should allow single-character filenames

lib/index.js
These need to be exported so that consumers can conveniently use the regexes in any of their `filenames/match-regex` overrides.
Follow-up to #30.
CC: @ghaagsma
=> Export filename regex utils

lib/config/typescript.js
Current state: `@typescript-eslint/no-unused-vars` warns when there is an unused parameter, even when it starts with an underscore.
Proposal: For Typescript, allow for unused-var parameters as long as they start with an `_`. The use of an underscore aligns with Typescript's implementation for skipping unused params: https://github.com/Microsoft/TypeScript/issues/9458
Documentation for eslint: https://eslint.org/docs/rules/no-unused-vars#argsignorepattern
=> Update warning for unused-vars in Typescript

lib/config/base.js, lib/config/react.js, lib/config/typescript.js
BREAKING CHANGE for next major release.
This rule is autofixable and thus easy to adopt. It's generally a minor but nice change.
https://eslint.org/docs/rules/sort-vars
=> Move `sort-vars` to `base` config

lib/config/base.js, lib/config/ember.js, lib/config/react.js, lib/config/typescript.js
BREAKING CHANGE: base will now error when filenames do not match kebab case
follow up to https://github.com/square/eslint-plugin-square/pull/30#discussion_r403385481
=> Enforce kebab-case filenames in `base` configuration

lib/config/ember.js
https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-private-routing-service.md
=> Enable `catchRouterMicrolib` option on `ember/no-private-routing-service` rule

.eslintrc.js, README.md, lib/config/base.js, package.json
This plugin has a large variety of amazing lint rules, especially for adopting new JavaScript syntax/functions, and most of them are autofixable. I've really enjoyed using them in some of my applications already.
Note that we are already using this plugin internally ourselves.
https://github.com/sindresorhus/eslint-plugin-unicorn
=> Enable eslint-plugin-unicorn recommended rules in `base` config

.eslintrc.js, .github/workflows/ci.yml, lib/rules/no-test-return-value.js, lib/rules/use-call-count-test-assert.js, package.json, yarn.lock
1. Formats .eslintrc.js (no longer ignored)
2. Updates CI tests to test under eslint 5, 6, and 7
3. Switches `token.start` / `token.end` to `token.range[0]` / `token.range[1]` (avoid using non-standard AST properties, see [RFC](https://github.com/eslint/rfcs/tree/master/designs/2019-rule-tester-improvements))
https://eslint.org/blog/2020/05/eslint-v7.0.0-released
=> Update to eslint 7 internally

lib/config/base.js
This is a new rule from eslint-plugin-unicorn v20: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-optional-catch-binding.md
Turn it off because:
1. Avoid it becoming a breaking change in our next minor release.
2. This is fairly new JavaScript syntax still: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch
Follow-up to: https://github.com/square/eslint-plugin-square/pull/70
=> Turn off unicorn/prefer-optional-catch-binding rule

README.md, docs/rules/no-restricted-files.md, lib/index.js, lib/rules/no-restricted-files.js, tests/lib/rules/no-restricted-files.js
See rule documentation.
My use case: I'm planning to manually enable this rule in one of my large applications to disallow unscoped/unnested components in the top-level components folder. Over time, the top-level components folder can become littered with a long, disorganized list of components with unclear ownership.
Somewhat inspired by rules like [no-restricted-imports](https://eslint.org/docs/rules/no-restricted-imports).
=> Add new rule `no-restricted-files`

docs/rules/no-restricted-files.md, lib/rules/no-restricted-files.js, tests/lib/rules/no-restricted-files.js
Better consistency with other `no-restricted-*` lint rules.
Rule has not been released yet. Follow-up to #80.
=> Rename `error` option to `message` in `no-restricted-files` rule

docs/rules/no-restricted-files.md, lib/rules/no-restricted-files.js
Several of our rules have commented-out autofixers that can be used to grandfather in existing violations.
=> Add commented-out autofixer to `no-restricted-files` rule

lib/config/base.js
https://github.com/selaux/eslint-plugin-filenames#matching-exported-values-match-exported
> Match the file name against the default exported value in the module. Files that dont have a default export will be ignored. The exports of index.js are matched against their parent directory.
=> Add `filenames/match-exported` rule to `base` config

lib/config/ember.js
https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-assignment-of-untracked-properties-used-in-tracking-contexts.md
=> Enable `no-assignment-of-untracked-properties-used-in-tracking-contexts` rule in `ember` config

README.md, package.json
Drop eslint 5 support (now that two newer versions are available: eslint 6 released 2019-06, eslint 7 released 2020-05).
It also helps that the ember-cli linting plugins have been deprecated (https://emberjs.github.io/rfcs/0121-remove-ember-cli-eslint.html) so pretty much everybody should be explicitly specifying eslint as a peer dependency at this point.
Fixes #86.
=> Drop ESLint 5 support

lib/config/typescript.js
ESLint 6+ supports using `extends` inside of `overrides`: https://eslint.org/blog/2019/06/eslint-v6.0.0-released
This prevents TypeScript lint rules from erroneously applying to JavaScript files.
Fixes #87.
=> Only enable TypeScript linting for `.ts` files in `typescript` config

.github/workflows/ci.yml
Since we dropped ESLint 5 support: https://github.com/square/eslint-plugin-square/pull/130
=> Stop testing under ESLint 5

lib/config/ember.js
For a few Ember file types (components, controllers, etc), this rule does not support the naming convention used by Ember's blueprint generator command.
And unfortunately, the rule doesn't allow providing a custom transform to support the desired naming convention.
https://github.com/selaux/eslint-plugin-filenames#matching-exported-values-match-exported
CC: @raycohen @mongoose700
=> Disable `filenames/match-exported` rule for certain Ember file types in `ember` config

lib/config/ember.js
This ensures the rule is disabled in the dummy test app (i.e. `tests/dummy/app/controllers`) and inside in-repo addons (i.e. `lib/some-subapp/app/controllers`).
=> Disable `filenames/match-exported` rule for dummy apps / subapps in `ember` config

lib/config/base.js
https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v21.0.0
=> Re-enable `unicorn/prefer-flat-map` rule in `base` config which was recently removed from eslint-plugin-unicorn's recommended config in v21.0.0

lib/config/ember.js, package.json, yarn.lock
Ember uses QUnit tests.
Fixes #194.
=> Add eslint-plugin-qunit to `ember` config

lib/config/ember.js
This makes the rule more strict and catch more potential issues. These options will be changed in the next major release of eslint-plugin-ember as well.
https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/require-super-in-init.md
=> Disable `checkInitOnly` and enable `checkNativeClasses` options on `ember/require-super-in-init rule` rule

lib/config/base.js
Too noisy:
```
Use default import for module `path`  unicorn/import-style
```
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/import-style.md
=> Turn off `unicorn/import-style` rule

lib/config/typescript.js
By enabling the appropriate parser for TypeScript files in this configuration, we avoid the need for consumers to add an override to do so themselves.
=> Enable @typescript-eslint/parser in `typescript` config

README.md, lib/config/strict.js, lib/config/typescript.js, lib/index.js
Our `typescript` configuration should only enable the recommended TypeScript rules, and not be further opinionated, since TypeScript can be used with any type of application. I moved the unrelated linting into a new (experimental?) `strict` configuration.
This is an alternative to #241 (enabling TypeScript linting in the `base` configuration) which avoids the need to add a dependency on the large `typescript` package (which I'm also worried might have unexpected side effects in non-typescript apps or apps using a different version of typescript).
=> Split `strict` config out of `typescript` config

lib/config/typescript.js
Reverts square/eslint-plugin-square#248
This doesn't appear to work unless we were to add `@typescript-eslint/parser` as a dependency, which would thus require `typescript` itself as a dependency, which we don't want to do.
```
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js » plugin:square/typescript#overrides[0]': Cannot find module '@typescript-eslint/parser'
```
=> Revert "Enable @typescript-eslint/parser in `typescript` config"

lib/config/ember.js
https://github.com/platinumazure/eslint-plugin-qunit/blob/master/docs/rules/no-assert-equal-boolean.md
Fixes #261.
=> Enable `qunit/no-assert-equal-boolean` rule in `ember` config

.eslintrc.js, tests/lib/rules/no-assert-ok-find.js, tests/lib/rules/no-handlebar-interpolation.js, tests/lib/rules/no-restricted-files.js, tests/lib/rules/no-test-return-value.js, tests/lib/rules/no-translation-key-interpolation.js, tests/lib/rules/require-await-function.js, tests/lib/rules/use-call-count-test-assert.js, tests/lib/rules/use-ember-find.js, tests/lib/utils/is-literal.js, tests/lib/utils/scope-reference-this.js
We can update to 2021 once we drop ESLint 6 support.
=> Use `ecmaVersion` 2020

lib/config/base.js
These are enabled by default as of #405 eslint-plugin-unicorn v32.
=> No longer need to manually enable unicorn flat rules

lib/rules/no-assert-ok-find.js, lib/rules/no-test-return-value.js
The change to require suggestable rules to have `meta.hasSuggestions` has been accepted and mentioned in the blog post for the upcoming ESLint 8 breaking changes. So we should adopt this change now to ensure we are compatible with ESLint 8 as soon as possible. The old property `meta.docs.suggestion` was unused anyway.
https://eslint.org/blog/2021/06/whats-coming-in-eslint-8.0.0#rules-with-suggestions-now-require-the-metahassuggestions-property
=> Use `meta.hasSuggestions` for suggestable rules to prepare for ESLint 8

README.md, docs/rules/no-assert-ok-find.md, docs/rules/no-test-return-value.md, docs/rules/no-translation-key-interpolation.md, docs/rules/require-await-function.md, docs/rules/use-call-count-test-assert.md, docs/rules/use-ember-find.md, tests/rule-setup.js
Just use the standard ones for the fixable/config emojis.
Code editors like VSCode can't render `:white_check_mark:` but they can render standard emojis like ✅. Standard emojis are more universal and don't require special rendering engines. Easier to work with and preview locally.
=> Switch from github emojis to standard emojis

.github/workflows/ci.yml
References:
* https://classic.yarnpkg.com/en/docs/cli/cache/#toc-change-the-cache-path-for-yarn
* https://github.com/actions/cache
=> Cache dependencies on GitHub Actions to speed up CI

.github/workflows/ci.yml
Follow-up to #463.
https://github.com/actions/setup-node#caching-packages-dependencies
=> Simplify CI dependency caching

.github/workflows/ci.yml, .npmpackagejsonlintrc.json, package.json, yarn.lock
Most importantly, this enforces the use of caret ranges for dependencies.
https://github.com/tclindner/npm-package-json-lint
=> Add `npm-package-json-lint`

lib/rules/no-assert-ok-find.js, lib/rules/no-handlebar-interpolation.js, lib/rules/no-missing-tests.js, lib/rules/no-restricted-files.js, lib/rules/no-test-return-value.js, lib/rules/no-translation-key-interpolation.js, lib/rules/require-await-function.js, lib/rules/use-call-count-test-assert.js, lib/rules/use-ember-find.js
Supported by VSCode/Webstorm/other code editors. Uses TypeScript declaration to give JavaScript hints so code editors can provide information/autocomplete about various rule fields.
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#type
Idea from: https://github.com/eslint/generator-eslint/pull/113
=> Add jsdoc `type` annotation to rules

docs/rules/no-assert-ok-find.md
We could eventually delete this rule from eslint-plugin-square once all its functionality is ported to the similar rule in eslint-plugin-qunit-dom.
CC: @Turbo87
https://github.com/square/eslint-plugin-square/blob/master/docs/rules/no-assert-ok-find.md
https://github.com/simplabs/eslint-plugin-qunit-dom/blob/main/rules/no-ok-find.md
=> Mention related rule `qunit-dom/no-ok-find` in `square/no-assert-ok-find` rule doc

.eslintrc.js, .npmpackagejsonlintrc.json, README.md, lib/config/base.js, lib/config/ember.js, lib/config/strict.js, package.json, yarn.lock
Before this change, it was provided in some of our configs but not all of them.
Now, consumers will never have to specify this, regardless of which of our configs they use:
```
plugins: ['square'],
```
Relies on this solution for internal linting of this plugin: https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/231
=> Automatically provide `square` plugin so consumers don't have to specify it

docs/rules/require-await-function.md, lib/rules/require-await-function.js, tests/lib/rules/require-await-function.js
This change allows for direct `return requiredAsyncFunc()`
Otherwise it conflicts with "no-return-await" rule of disallowing `return await requiredAsyncFunc();`
=> Don't require `await` in return statements in `require-await-function` rule

.github/dependabot.yml
For our `dependencies` in package.json, we need to update their versions in both package.json and the lockfile, not just the lockfile, for the update to have an effect on consumers. If we only update a version in the lockfile, it will affect us, but not consumers of this plugin.
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#versioning-strategy
=> Tell dependabot to increase versions in package.json

lib/utils/async-ember-test-helpers.js
In the `ember` config, we store a list of the Ember async test helpers that should be called with `await` as enforced by the [square/require-await-function](https://github.com/square/eslint-plugin-square/blob/master/docs/rules/require-await-function.md) rule.
This PR improves the completeness of this list.
https://github.com/emberjs/ember-test-helpers/blob/master/API.md
=> Add more async Ember test helpers

README.md, package.json
This matches ESLint 8, which we now require:
* https://github.com/square/eslint-plugin-square/pull/586
=> Drop support for old minor versions of Node 12 and 14

lib/index.js
Needed since this array can no longer be accessed directly:
* #587
Before:
```js
const ASYNC_EMBER_TEST_HELPERS = require('eslint-plugin-square/lib/utils/async-ember-test-helpers');
```
After:
```js
const { utils } = require('eslint-plugin-square');
console.log(utils.ASYNC_EMBER_TEST_HELPERS);
```
=> Expose `ASYNC_EMBER_TEST_HELPERS` in public Node API

docs/rules/no-translation-key-interpolation.md, lib/rules/no-translation-key-interpolation.js, tests/lib/rules/no-translation-key-interpolation.js
Allows users to enforce stricter rules on translation keys by only allowing string literals as keys. Previously, rule would allow keys that are functions or variables.
`yarn test`  
`yarn eslint .`
=> Add `enforceStringLiteralKeys` option to `no-translation-key-interpolation` rule

.github/workflows/ci.yml, README.md, package.json
Drop Node 12 support (end-of-life 2022-04-30).
Drop Node 17 support (end-of-life 2022-06-01).
Require Node 14.18 minimum so that we can adopt `node:` protocol imports like eslint-plugin-unicorn:
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/20e959ffadeca007697534f1ad58c45d29cfdb04/package.json#L14
=> Drop support for Node 12 and Node 17

README.md, package.json
Necessary to upgrade to the latest version of eslint-plugin-unicorn which added this requirement:
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/20e959ffadeca007697534f1ad58c45d29cfdb04/package.json#L93
=> Drop support below ESLint 8.18.0

.eslintrc.js, lib/config/base.js, lib/rules/no-missing-tests.js, lib/utils/import.js, tests/config-setup.js, tests/lib/rules/no-missing-tests.js, tests/lib/utils/filenames.js, tests/lib/utils/imports.js, tests/lib/utils/is-literal.js, tests/lib/utils/is-test-file.js, tests/rule-setup.js
Not enabling in our public `base` config yet since some libraries using eslint-plugin-square may still want to support earlier versions of Node 14 where this feature is not available yet, so we won't enforce this on others until we drop support for Node 14 entirely in 2023.
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-node-protocol.md
=> Enable `unicorn/prefer-node-protocol` rule internally

RELEASE.md, package.json, yarn.lock
> This package has been renamed to @release-it-plugins/lerna-changelog
https://github.com/release-it-plugins/lerna-changelog
=> Move from deprecated `release-it-lerna-changelog` to `@release-it-plugins/lerna-changelog`

lib/config/base.js, lib/config/typescript.js
This would allow the file `model.d.ts` to export something named `Model`.
=> Handle `.d.ts` files correctly for `filenames/match-exported` rule

docs/rules/no-restricted-files.md, lib/rules/no-restricted-files.js, tests/lib/rules/no-restricted-files.js
The `paths` option is useful if you want to use regexp to match filenames to disallow. If you want to instead use glob patterns, ESLint's built-in [glob pattern overrides feature](https://eslint.org/docs/latest/user-guide/configuring/configuration-files#configuration-based-on-glob-patterns) should be used, and `paths` shouldn't be needed. This change optimizes the rule for the glob-based use-case so you don't have to specify a wildcard like `paths: ['.+']`.
=> `paths` option is now optional in `no-restricted-files` rule

.markdownlint.json, README.md, docs/rules/_TEMPLATE_.md, docs/rules/no-assert-ok-find.md, docs/rules/no-missing-tests.md, docs/rules/no-restricted-files.md, docs/rules/no-test-return-value.md, docs/rules/no-translation-key-interpolation.md, docs/rules/require-await-function.md, docs/rules/use-call-count-test-assert.md, docs/rules/use-ember-find.md
Before this change, whatever list style was used first in a file would be enforced for that file. Now, let's standardize on dashes. This is all autofixed by the lint rule.
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md004---unordered-list-style
This is also the [standard enforced by prettier for markdown](https://github.com/prettier/prettier/issues/4251) which we may adopt later.
=> Switch to dash for markdown lists

README.md, docs/rules/no-assert-ok-find.md, docs/rules/no-handlebar-interpolation.md, docs/rules/no-missing-tests.md, docs/rules/no-restricted-files.md, docs/rules/no-test-return-value.md, docs/rules/no-translation-key-interpolation.md, docs/rules/require-await-function.md, docs/rules/use-call-count-test-assert.md, docs/rules/use-ember-find.md, package.json, tests/rule-setup.js, yarn.lock
I built this CLI tool [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator) for automating the README rules list and the title/notices in each rule doc. It follows common documentation conventions from other ESLint plugins. The goal is to improve the usability of our custom rules through better documentation and make it easier to add new rules by automating more of the process. I was also able to remove tests that are now redundant.
=> Automate docs with eslint-doc-generator

README.md, docs/rules/no-assert-ok-find.md, docs/rules/no-handlebar-interpolation.md, docs/rules/no-missing-tests.md, docs/rules/no-restricted-files.md, docs/rules/no-test-return-value.md, docs/rules/no-translation-key-interpolation.md, docs/rules/require-await-function.md, docs/rules/use-call-count-test-assert.md, docs/rules/use-ember-find.md, package.json, yarn.lock
Lots of improvements from `0.3.5` to https://github.com/bmish/eslint-doc-generator/releases/tag/v0.16.0.
For example, the legend for the rules list is now auto-generated.
=> Update eslint-doc-generator to 0.16

lib/config/typescript.js
- Adds `_*` as an ignore pattern for variables and array destructuring in no-unused-vars
We already allow `_` prefix for function arguments, and the same case could be made for other usages as well.
For a concrete example: Suppose I want to split a SemVer string but only care about the major version.
My options today are:
```ts
const [major] = semVer.split(".")
const [major, , ] = semVer.split(".")
const [major, /* minor, patch */] = semVer.split(".")
```
None of these read well and I'd like to be able to use `const [major, _minor, _patch] = semVer.split(".")`
In general though, with the _ prefix used to declare intention to allow an ignored variable we might as well expand that definition out.
=> Allow all unused vars with leading `_` in `typescript` config

lib/config/ember.js
This rule triggers in CI after creating a new addon in Dashboard. [Example build part](https://kochiku-production-build-logs.s3.us-west-2.amazonaws.com/squareup/dashboard/build_6321230/part_322014409/attempt_277137685/stdout.log.gz?X-Amz-Expires=604800&X-Amz-Date=20221205T160212Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIBPRFGE3IOTXUBCA%2F20221205%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=069d5b3769ded56a17e1120a7680ce05e0f9f39660ad750db6e428ca7b0e3b75).
```
/data/app/kochiku-worker/shared/build-partition/squareup/dashboard/frontend/@dashboard/ember-cli-csso/tests/dummy/app/config/environment.d.ts
5:1  error  Filename 'environment' must match the exported and transformed name 'config'  filenames/match-exported
```
The generated code is defined …
=> Disable `filenames/match-exported` rule for generated `config/environment.d.ts` in `ember` config

lib/config/base.js, lib/config/typescript.js
Not all users use our `typescript` config but they still might have TypeScript files. This part of the `typescript` config we can automatically apply in the `base` config for TypeScript files only.
https://github.com/import-js/eslint-plugin-import/blob/main/config/typescript.js
Note that we can't move the `@typescript-eslint/recommended` parts of the `typescript` config to `base` because we don't want to add a package.json dependency on `typescript` (tried in https://github.com/square/eslint-plugin-square/pull/250 https://github.com/square/eslint-plugin-square/pull/241).
=> Automatically use `import/typescript` config in `base` config for TypeScript files

README.md, lib/config/base.js, package.json
We already suggested this in the README, but we can actually ensure it's enabled for everybody in our shared configs.
Note that it is only possible to warn with this feature (erroring not possible yet, although I've written an RFC regarding this: https://github.com/eslint/rfcs/pull/100).
https://eslint.org/docs/latest/user-guide/configuring/rules#report-unused-eslint-disable-comments
=> Warn on unused ESLint disable directives in `base` config

lib/config/base.js, lib/config/typescript.js, lib/rules/no-missing-tests.js, lib/utils/is-test-file.js, tests/lib/utils/is-test-file.js
Currently, TypeScript-specific rules in the `typescript` config apply to `.ts` files but not `.tsx` files. This PR simply adds the `.tsx` extension to the `files` array.
=> Apply TypeScript rules to additional file types

.eslintrc.js, .github/workflows/ci.yml, README.md, lib/config/base.js, package.json
EOL 2023-04-30. blocking dependency upgrades (like #882 which will address #880)
https://github.com/nodejs/release#end-of-life-releases
=> feat!: drop Node v14 support

lib/rules/no-missing-tests.js, tests/lib/rules/no-missing-tests.js
Currently, if multiple options that match the `filePath` of a file are present, only the first option's testPaths are considered. We want to accept a test from any matching option.
- First commit adds a reproduction test case
- Second commit adds a fix
=> Fix no-missing-tests bug when multiple matching options are present

README.md
ESM projects need to use a `.eslintrc.cjs` file for configuration. The current note only mentions `.eslintrc.js` which was causing some confusion and errors for people creating new ESM projects.
=> docs: add note on ESLint configuration files

.github/workflows/release-linter.yml, .github/workflows/release.yml, RELEASE.md
Introduces automation for release management and updates the release instructions to reflect the new process. 
We are adding GitHub workflows for validating PR titles and automating the release process, as well as updating the `RELEASE.md` file to document the new release workflow.
Before merging:
=> chore: Introduce Block OSPO Releaser

RELEASE.md
Add bypass instructions to release.
This should be temporary while we evolve the Releaser to use an App to open the Release PR.
=> docs: add release bypass instructions
